/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package INTERFACES;


import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

    


/**
 *
 * @author Ale
 */
public class LOGIN extends javax.swing.JFrame {
public String usuario;
public String clave;
public static Connection cn;
public static Statement st;
public static ResultSet rs;
    
    /**
     * Creates new form LOGIN
     */
    public LOGIN() {
      
        initComponents();
        
         this.setLocationRelativeTo(null);
        
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        usuarioingreso = new javax.swing.JTextField();
        claveingreso = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ingresoboton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("AUTOCASHER");
        jLabel3.setToolTipText("");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 170, 50));

        usuarioingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioingresoActionPerformed(evt);
            }
        });
        getContentPane().add(usuarioingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 190, 30));

        claveingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claveingresoActionPerformed(evt);
            }
        });
        getContentPane().add(claveingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 190, 30));

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("UNO SIEMPRE CERCA DE USTED.");
        jLabel6.setToolTipText("");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 210, 50));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("USUARIO");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CLAVE:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/User.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -40, 330, 330));

        jButton1.setText("exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        ingresoboton.setBackground(new java.awt.Color(255, 255, 255));
        ingresoboton.setText("INGRESO");
        ingresoboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresobotonActionPerformed(evt);
            }
        });
        getContentPane().add(ingresoboton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/FondoAzul.png"))); // NOI18N
        jLabel1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jLabel1ComponentAdded(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 420));

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jLabel1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1ComponentAdded

    private void usuarioingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioingresoActionPerformed
        // TODO add your handling code here:
       
    
     

  

    }//GEN-LAST:event_usuarioingresoActionPerformed
public void conectar()
{
    try {
        String url="jdbc:oracle:thin:@localhost:1521:XE";
    cn = DriverManager.getConnection(url, "ALEJANDRO","HP");
    st = cn.createStatement();       
  

    }
    catch (Exception e)
    {
        JOptionPane.showMessageDialog(null,"no se pudo conectar)"+e);
    }
}
 



    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ingresobotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresobotonActionPerformed
    
        // TODO add your handling code here:
        
        
        usuario=usuarioingreso.getText();
        clave=String.valueOf(claveingreso.getPassword());
       
        
       
        System.out.println(usuario);
        
        
        
        
        
        conectar();
        
        System.out.println("su usuario es "+usuario);
        
       try { 
        
        
        
        String consulta="Select*from LOGIN where USUARIO_LOGIN='"+usuario+"'AND CONTRASEÑA_LOGIN=('"+clave+"')";
        
        rs=st.executeQuery(consulta);
        rs=st.getResultSet();
        
        
        
        
        if( rs.next()){
            JOptionPane.showMessageDialog(null, "su usuario es valido");
           dispose();
            
            new MENU().setVisible(true);
            
        }
        else
        {
            JOptionPane.showMessageDialog(null, "su usuario es invalido");
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "su usuario es invalido"+ex);
    }
              
    
   
    }//GEN-LAST:event_ingresobotonActionPerformed

    
     
     
    public static void setUsuarioingreso(JTextField usuarioingreso) {
        LOGIN.usuarioingreso = usuarioingreso;
    }

    public static JTextField getUsuarioingreso() {
        return usuarioingreso;
    }
    

  

    private void claveingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claveingresoActionPerformed
        
       
   
    }//GEN-LAST:event_claveingresoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LOGIN().setVisible(true);
         
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField claveingreso;
    private javax.swing.JButton ingresoboton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JTextField usuarioingreso;
    // End of variables declaration//GEN-END:variables

  
 
}
