/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package INTERFACES;

import static INTERFACES.LOGIN.rs;
import static INTERFACES.LOGIN.st;
import static INTERFACES.retiromonetario.igualacionmonetario;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;

/**
 *
 * @author Ale
 */
public class MENU extends javax.swing.JFrame {

    /**
     * Creates new form MENU
     */
    public static String igualacion;
    public MENU() {
        initComponents();
        this.igualacion=LOGIN.usuarioingreso.getText();
        this.setLocationRelativeTo(null);
    }
     public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("IMAGENES/appleLogo.PNG"));
        return retValue;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        retiromonetarioboton = new javax.swing.JButton();
        retiroahorro = new javax.swing.JButton();
        retiromonetarioboton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        consultarahorro = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jButton3.setText("*");

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Bazaronite", 1, 24)); // NOI18N
        jLabel3.setText("RETIRO AHORRO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 270, 60));

        jLabel5.setFont(new java.awt.Font("Bazaronite", 1, 18)); // NOI18N
        jLabel5.setText("CAMBIO DE CLAVE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 220, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/avatar.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 130, 140));

        jLabel2.setFont(new java.awt.Font("Bazaronite", 1, 24)); // NOI18N
        jLabel2.setText("CONSULTA AHORRO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 290, 60));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/FLECHA DER.PNG"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 100, -1));

        retiromonetarioboton.setBackground(new java.awt.Color(255, 255, 255));
        retiromonetarioboton.setForeground(new java.awt.Color(255, 255, 255));
        retiromonetarioboton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/FLECHA DER.PNG"))); // NOI18N
        retiromonetarioboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retiromonetariobotonActionPerformed(evt);
            }
        });
        getContentPane().add(retiromonetarioboton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 100, -1));

        retiroahorro.setBackground(new java.awt.Color(255, 255, 255));
        retiroahorro.setForeground(new java.awt.Color(255, 255, 255));
        retiroahorro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/FELCHA IZ.PNG"))); // NOI18N
        retiroahorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retiroahorroActionPerformed(evt);
            }
        });
        getContentPane().add(retiroahorro, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 100, -1));

        retiromonetarioboton1.setBackground(new java.awt.Color(255, 255, 255));
        retiromonetarioboton1.setForeground(new java.awt.Color(255, 255, 255));
        retiromonetarioboton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/FLECHA DER.PNG"))); // NOI18N
        retiromonetarioboton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retiromonetarioboton1ActionPerformed(evt);
            }
        });
        getContentPane().add(retiromonetarioboton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 100, -1));

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("AUTOCASHER");
        jLabel7.setToolTipText("");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 170, 50));

        jLabel4.setFont(new java.awt.Font("Bazaronite", 1, 24)); // NOI18N
        jLabel4.setText("RETIRO MONETARIO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 310, 60));

        consultarahorro.setBackground(new java.awt.Color(255, 255, 255));
        consultarahorro.setForeground(new java.awt.Color(255, 255, 255));
        consultarahorro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/FELCHA IZ.PNG"))); // NOI18N
        consultarahorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarahorroActionPerformed(evt);
            }
        });
        getContentPane().add(consultarahorro, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 100, -1));

        jLabel9.setFont(new java.awt.Font("Bazaronite", 1, 24)); // NOI18N
        jLabel9.setText("CONSULTA MONETARIA");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 350, 60));

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("UNO SIEMPRE CERCA DE USTED.");
        jLabel8.setToolTipText("");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 210, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/FondoAzul.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retiromonetariobotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retiromonetariobotonActionPerformed
        // TODO add your handling code here:
        dispose();
        new consultar().setVisible(true);
    }//GEN-LAST:event_retiromonetariobotonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
       
        new  LOGIN().setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void retiroahorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retiroahorroActionPerformed
        // TODO add your handling code here:
              
               
        dispose();
        
        new retiroahorro().setVisible(true);
    }//GEN-LAST:event_retiroahorroActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
         dispose();
       new CAMBIA_PIN().setVisible(true);
     
    }//GEN-LAST:event_jButton4ActionPerformed

    private void retiromonetarioboton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retiromonetarioboton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new retiromonetario().setVisible(true);
    }//GEN-LAST:event_retiromonetarioboton1ActionPerformed

    private void consultarahorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarahorroActionPerformed
        // TODO add your handling code here:
        dispose();
        new CONSULTAR2().setVisible(true);
    }//GEN-LAST:event_consultarahorroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultarahorro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton retiroahorro;
    private javax.swing.JButton retiromonetarioboton;
    private javax.swing.JButton retiromonetarioboton1;
    // End of variables declaration//GEN-END:variables
}
