/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package INTERFACES;

import static INTERFACES.LOGIN.rs;
import static INTERFACES.LOGIN.st;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author Ale
 */
public class retiroahorro extends javax.swing.JFrame {



    public static String igualacionahorro;

   /**
     * Creates new form retiroahorro
    
     */
    public retiroahorro(){
        initComponents();
        this.igualacionahorro=LOGIN.usuarioingreso.getText();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/FLECHA DER.PNG"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 100, -1));

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/FLECHA DER.PNG"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 100, -1));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/FLECHA DER.PNG"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 100, -1));

        jLabel11.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        jLabel11.setText("1000");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 80, 70));

        jLabel10.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        jLabel10.setText("300");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 70, 70));

        jLabel9.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        jLabel9.setText("100");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 70, 70));

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("ATRAS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 80, 50));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/FELCHA IZ.PNG"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 100, -1));

        jLabel8.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        jLabel8.setText("2000");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 90, 70));

        jLabel13.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        jLabel13.setText("500");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 70, 70));

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/FELCHA IZ.PNG"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 100, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/FELCHA IZ.PNG"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 100, -1));

        jLabel12.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        jLabel12.setText("200");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 70, 70));

        jLabel5.setFont(new java.awt.Font("Bazaronite", 1, 24)); // NOI18N
        jLabel5.setText("RETIRO AHORRO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 320, 60));

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("AUTOCASHER");
        jLabel7.setToolTipText("");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 170, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/FondoAzul.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        
        new MENU().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
      
      int monto1=100;
       this.setLocationRelativeTo(null);
       
    
       
        try { 
          LOGIN L=new LOGIN();
      L.conectar();
        
        
        String consulta="update CUENTA_AHORROS set SALDO_TOTAL= SALDO_TOTAL-'"+monto1+"' where USUARIO_CUENTA_AHORRO='"+igualacionahorro+"'AND SALDO_TOTAL>='"+monto1+"'";
        
        rs=st.executeQuery(consulta);
        rs=st.getResultSet();
        dispose();
        
          
       new RETIRO_EXITOSO().setVisible(true);
       
    } catch (SQLException ex) {
      
                 new ERROR_RETIRO().setVisible(true);
    }
              
        
      
    
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          int monto2=200;
       this.setLocationRelativeTo(null);
       
    
       
        try { 
          LOGIN L=new LOGIN();
      L.conectar();
        
        
        String consulta="update CUENTA_AHORROS set SALDO_TOTAL= SALDO_TOTAL-'"+monto2+"' where USUARIO_CUENTA_AHORRO='"+igualacionahorro+"'AND SALDO_TOTAL>='"+monto2+"'";
        
        rs=st.executeQuery(consulta);
        rs=st.getResultSet();
        dispose();
        
          
       new RETIRO_EXITOSO().setVisible(true);
       
    } catch (SQLException ex) {
      
                 new ERROR_RETIRO().setVisible(true);
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
          int monto3=300;
       this.setLocationRelativeTo(null);
       
    
       
        try { 
          LOGIN L=new LOGIN();
      L.conectar();
        
        
        String consulta="update CUENTA_AHORROS set SALDO_TOTAL= SALDO_TOTAL-'"+monto3+"' where USUARIO_CUENTA_AHORRO='"+igualacionahorro+"'AND SALDO_TOTAL>='"+monto3+"'";
        
        rs=st.executeQuery(consulta);
        rs=st.getResultSet();
        dispose();
        
          
       new RETIRO_EXITOSO().setVisible(true);
       
    } catch (SQLException ex) {
      
                 new ERROR_RETIRO().setVisible(true);
    }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
          int monto4=500;
       this.setLocationRelativeTo(null);
       
    
       
        try { 
          LOGIN L=new LOGIN();
      L.conectar();
        
        
        String consulta="update CUENTA_AHORROS set SALDO_TOTAL= SALDO_TOTAL-'"+monto4+"' where USUARIO_CUENTA_AHORRO='"+igualacionahorro+"'AND SALDO_TOTAL>='"+monto4+"'";
        
        rs=st.executeQuery(consulta);
        rs=st.getResultSet();
        dispose();
        
          
       new RETIRO_EXITOSO().setVisible(true);
       
    } catch (SQLException ex) {
      
                 new ERROR_RETIRO().setVisible(true);
    }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
          int monto5=1000;
       this.setLocationRelativeTo(null);
       
    
       
        try { 
          LOGIN L=new LOGIN();
      L.conectar();
        
        
        String consulta="update CUENTA_AHORROS set SALDO_TOTAL= SALDO_TOTAL-'"+monto5+"' where USUARIO_CUENTA_AHORRO='"+igualacionahorro+"'AND SALDO_TOTAL>='"+monto5+"'";
        
        rs=st.executeQuery(consulta);
        rs=st.getResultSet();
        dispose();
        
          
       new RETIRO_EXITOSO().setVisible(true);
       
    } catch (SQLException ex) {
      
                 new ERROR_RETIRO().setVisible(true);
    }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
          int monto6=2000;
       this.setLocationRelativeTo(null);
       
    
       
        try { 
          LOGIN L=new LOGIN();
      L.conectar();
        
        
        String consulta="update CUENTA_AHORROS set SALDO_TOTAL= SALDO_TOTAL-'"+monto6+"' where USUARIO_CUENTA_AHORRO='"+igualacionahorro+"'AND SALDO_TOTAL>='"+monto6+"'";
        
        rs=st.executeQuery(consulta);
        rs=st.getResultSet();
        dispose();
        
          
       new RETIRO_EXITOSO().setVisible(true);
       
    } catch (SQLException ex) {
      
                 new ERROR_RETIRO().setVisible(true);
    }
    }//GEN-LAST:event_jButton6ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(retiroahorro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(retiroahorro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(retiroahorro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(retiroahorro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new retiroahorro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}

